[package]
name = "tui-patch"
version = "0.1.0"
authors = ["Roland Mueller <rmu@zuehlke.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "~0.8"
serde = { version = "~1.0", features = ["derive"] }
serde_yaml = "~0.8"
indicatif = "~0.14"
chrono = "~0.4"